name: Publish dev-box Docker Image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Run build-pre.sh
        working-directory: ./src/dev-box/build
        run: |
          chmod +x ./build-pre.sh
          ./build-pre.sh
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/dev-box
          file: ./src/dev-box/build/dev-box.common.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dev-box:${{ env.RELEASE_VERSION }}
