name: Publish internal-storage Docker Image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push internal-storage-barrier to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/internal-storage
          file: ./src/internal-storage/build/internal-storage-barrier.k8s.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/internal-storage-barrier:${{ env.RELEASE_VERSION }}
      - name: Push internal-storage-create to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/internal-storage
          file: ./src/internal-storage/build/internal-storage-create.k8s.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/internal-storage-create:${{ env.RELEASE_VERSION }}
      - name: Push internal-storage-delete to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/internal-storage
          file: ./src/internal-storage/build/internal-storage-delete.k8s.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/internal-storage-delete:${{ env.RELEASE_VERSION }}
