name: Publish prometheus-pushgateway Docker Image

on:
  release:
    types: [published]
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta-metrics-cleaner
        id: meta-metrics-cleaner
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login || secrets.DOCKERHUB_USERNAME }}/metrics-cleaner
          flavor: |
            latest=auto
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
      - name: Push metrics-cleaner to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./src/prometheus-pushgateway
          file: ./src/prometheus-pushgateway/build/metrics-cleaner.common.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-metrics-cleaner.outputs.tags }}
          labels: ${{ steps.meta-metrics-cleaner.outputs.labels }}

      - name: Docker meta-prometheus-pushgateway
        id: meta-prometheus-pushgateway
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login || secrets.DOCKERHUB_USERNAME }}/prometheus-pushgateway
          flavor: |
            latest=auto
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
      - name: Push prometheus-pushgateway to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./src/prometheus-pushgateway
          file: ./src/prometheus-pushgateway/build/prometheus-pushgateway.common.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-prometheus-pushgateway.outputs.tags }}
          labels: ${{ steps.meta-prometheus-pushgateway.outputs.labels }}
