name: Publish database-controller Docker Image

on: [push]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run build-pre.sh
        working-directory: ./src/database-controller/build
        run: |
          chmod +x ./build-pre.sh
          ./build-pre.sh
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/database-controller
          file: ./src/database-controller/build/database-controller.common.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/database-controller:test
