name: Publish node-exporter:test Docker Image

on: [push]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/node-exporter
          file: ./src/node-exporter/build/node-exporter.common.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-exporter:test
